var myFullName;
console.log(myFullName);
 myFullName="Mayur Gavade";
console.log(myFullName);
 myFullName="Mayur Ashok Gavade";
 console.log(myFullName);
 var myLove="I love only JS";
 console.log(myLove);
 var firstName="Mayur";
 console.log("First Name: "+firstName);
 var lastName="Gavade";
 console.log("Last Name: "+lastName);
var age="22";
console.log("Age: "+age);
var address="Pune";
console.log("Address: "+address);
var pinCode="412307";
console.log("Pincode: "+pinCode);
var gender="Male";
console.log("Gender: "+gender);
var isMarried="Unmarried";
console.log("Status: "+isMarried);