console.log("===============Assignment-1==================");
console.log("===============Step-1(Number)========================");
var shirtNo=7;
console.log("Shirt-NO= "+shirtNo);
console.log("Datatype= "+ typeof shirtNo);
console.log("-------------------------------------------------");
var iplTrophies=5;
console.log("IPL Trophies= "+iplTrophies);
console.log("Datatype= "+ typeof iplTrophies);
console.log("-------------------------------------------------");
var runs=5500;
console.log("Runs= "+runs);
console.log("Datatype= "+ typeof runs);
console.log("===============Step-2(String)========================");
var plyerName="MS Dhoni";
console.log("Player Name= "+plyerName);
console.log("Datatype= "+ typeof plyerName);
console.log("-------------------------------------------------");
var team="Chennai Super Kings";
console.log("Team= "+team);
console.log("Datatype= "+ typeof team);
console.log("-------------------------------------------------");
var nativePlace="Ranchi";
console.log("Native Place= "+nativePlace);
console.log("Datatype= "+ typeof nativePlace);
console.log("===============Step-3(Boolean)========================");
var isCricketer=true;
console.log("IS Cricketer= "+isCricketer);
console.log("Datatype= "+ typeof isCricketer);
console.log("-------------------------------------------------");
var isBowler=false;
console.log("IS Bowler= "+isBowler);
console.log("Datatype= "+ typeof isBowler);
console.log("-------------------------------------------------");
var isWicketKeeper=true;
console.log("IS Wicket-keeper= "+isWicketKeeper);
console.log("Datatype= "+ typeof isWicketKeeper);

console.log("===============null vs undefined========================");
var price=null;
console.log("Price= "+price);
console.log("Datatype= "+ typeof price);
console.log("-------------------------------------------------------");
var value;
console.log("value= "+value);
console.log("Datatype= "+typeof value);
console.log("-------------------------------------------------------");
console.log("(1) Null=Null means not equal to zero or unknown value");
console.log("(2) Undefined= When variable is not initialized only declared then considered as undefined");